Simple-as-Coding/tutoring-platform

.gitignore, pom.xml, src/main/java/pl/simpleascoding/tutoringplatform/TutoringPlatformApplication.java, src/main/resources/application.properties, src/test/java/pl/simpleascoding/tutoringplatform/TutoringPlatformApplicationTests.java
-pom.xml dependencies added
-application.properties configured
=> Basic Configuration

src/main/java/pl/simpleascoding/tutoringplatform/domain/user/Role.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/user/User.java
- Changed user, role tables name
- Changed user-role relation from ManyToMany to OneToMany
=> Entity role, user

docs/api/authentication.md, docs/api/registration.md
-fixed md for authentication & registration
-Author @dawciobiel
=> fix: docs/authentication,registration

src/main/java/pl/simpleascoding/tutoringplatform/filter/JwtAuthenticationFilter.java, src/main/java/pl/simpleascoding/tutoringplatform/service/userDetails/UserDetailsServiceImpl.java
- Fixed security implementation by adding back UserDetailsServiceImpl class
=> Security implementation fix

src/main/resources/bundle_en_US.properties, src/main/resources/bundle_pl_PL.properties
Added languages properties bundles
=> Internationalization

docs/internationalization/internationalization.md, docs/internationalization/todo_internationalization.md
Initial commit
Added few links
Added todo internationalization list // This list will be deleted in the future
=> docs internationalization

src/main/java/pl/simpleascoding/tutoringplatform/api/publicResource/UserController.java, src/main/java/pl/simpleascoding/tutoringplatform/config/WebSecurityConfig.java, src/main/java/pl/simpleascoding/tutoringplatform/dto/ChangeUserPasswordDTO.java, src/main/java/pl/simpleascoding/tutoringplatform/service/user/UserFacade.java, src/main/java/pl/simpleascoding/tutoringplatform/service/user/UserService.java, src/main/java/pl/simpleascoding/tutoringplatform/service/user/UserServiceImpl.java
- Added 'password change' method declarations to the interface
- Implementations of this service method have been added
- Controller created
=> Feature password changing

src/main/java/pl/simpleascoding/tutoringplatform/dto/ChangeUserPasswordDTO.java, src/main/java/pl/simpleascoding/tutoringplatform/service/user/UserServiceImpl.java
Refactored service method of changing user password
Refactored method of verifying password matching
Refactored naming of the methods, variables, and arguments
Refactored code formatting
Added java doc documentation
=> refactor: UserServiceImpl

docs/swagger/swaggerdoc.md, pom.xml, src/main/java/pl/simpleascoding/tutoringplatform/config/SwaggerConfig.java, src/main/resources/application.properties
Swagger added
- Added necessary dependencies for Swagger
- Created SwaggerConfig which's ```@Configuration``` class
- Created Docket method which's ```@Bean``` in SwaggerConfig class
- Added necessary property in application properties file
- Created Swagger documentation
=> Feature_add_swagger

src/main/java/pl/simpleascoding/tutoringplatform/domain/tutoring/OfferType.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/tutoring/TutoringOffer.java
Tutoring Offer
Modification TutoringOffer class
Modification OfferType enum
=> Tutoring offer

docs/docker-postgres/install.md, docs/docker/install.md, docs/docker/uninstall.md, docs/postgres/postgres.md
-refactoring installation documentation for Docker
-added documentation for uninstall Docker
-created installation documentation for Postgres on Docker
=> docs: Docker, Postgres on Docker, Postgres documentations

docs/clean-code/dry.md, docs/clean-code/kiss.md, docs/clean-code/occams_razora.md, docs/clean-code/solid.md, docs/clean-code/yagni.md
-Brzytwa Ockhama
-DRY
-KISS
-Occam's razor
-SOLID
-YAGNI
=> docs: Added documentation for clean code

docs/spring/design_patterns.md
-added initial documentation for Spring Framework design patterns
=> docs: Spring Framework

docs/spring/ResponseEntity_vs_ResponseBody_vs_ResponseStatus.md
-ResponseEntity vs annotation ResponseBody vs annotation ResponseStatus
=> docs: Added documentation for controller response

src/main/java/pl/simpleascoding/tutoringplatform/api/LoginController.java, src/main/java/pl/simpleascoding/tutoringplatform/api/RefreshController.java, src/main/java/pl/simpleascoding/tutoringplatform/api/TestApi.java, src/main/java/pl/simpleascoding/tutoringplatform/api/UserController.java
-Moved TestApi, Login, Refresh, User Controllers to parent api package,
-Removed publicResource child package of api package.
=> style: publicResource package removal,

src/main/java/pl/simpleascoding/tutoringplatform/exception/EmailTakenException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/InvalidTokenException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/MissingParametersException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/MissingRefreshTokenException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/ReviewNotFoundException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/TokenAlreadyConfirmedException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/TokenNotFoundException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/UserAlreadyEnabledException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/UserNotFoundException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/UsernameTakenException.java
- add response status to exceptions classes
- changed exception types if necessery
- some style refacoring
=> Refactor of exception classes 

src/main/java/pl/simpleascoding/tutoringplatform/api/TeacherController.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/user/Role.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/user/RoleType.java, src/main/java/pl/simpleascoding/tutoringplatform/dto/SignAsTeacherDTO.java, src/main/java/pl/simpleascoding/tutoringplatform/dto/TeacherDTO.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/UserIsAlreadyATeacherException.java, src/main/java/pl/simpleascoding/tutoringplatform/repository/RoleRepository.java, src/main/java/pl/simpleascoding/tutoringplatform/service/teacher/TeacherService.java, src/main/java/pl/simpleascoding/tutoringplatform/service/teacher/TeacherServiceImpl.java, src/main/java/pl/simpleascoding/tutoringplatform/service/user/UserModelMapper.java
- created teacher controller
- added new role
- added signasteacherdto
- added teacherdto
- added userisalreadyateacherexception exception class
- added find all roles by roletype method
- created teacher service class and created find all teachers method and add teacher role to user method
- created teacher service implementation and implemented methods
- added hashCode and equals methods to role entity
=> Feature signing user as teacher, and finding all teachers

src/main/java/pl/simpleascoding/tutoringplatform/exception/EmailTakenException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/InvalidTokenException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/MissingParametersException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/MissingRefreshTokenException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/TokenAlreadyConfirmedException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/TokenNotFoundException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/UserAlreadyEnabledException.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/UsernameTakenException.java
Moved exception messages to final fields
=> Exceptions refactor

src/main/java/pl/simpleascoding/tutoringplatform/dto/RscpDTO.java, src/main/java/pl/simpleascoding/tutoringplatform/rscp/RscpStatus.java, src/main/java/pl/simpleascoding/tutoringplatform/rscp/package-info.java
-Create enum service to controller status codes.
-Create record (DTO) class to share information between Services and Controllers.
=> feat: Response Service to Controller Protocol

src/main/java/pl/simpleascoding/tutoringplatform/domain/token/Token.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/user/Role.java
According with the guidelines in this article https://stackabuse.com/guide-to-jpa-with-hibernate-basic-mapping/ I added @Enumerated annotation in 2 entities: Token and Role
=> Refactor Token and Role

src/main/java/pl/simpleascoding/tutoringplatform/api/ReviewController.java, src/main/java/pl/simpleascoding/tutoringplatform/api/UserController.java
I changed ResponseEnitity in controlleres to return HttpStatus from RscpDto
=> Refactor controllers

src/main/java/pl/simpleascoding/tutoringplatform/api/AdvertisementController.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/advertisement/Advertisement.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/advertisement/AdvertisementCategory.java, src/main/java/pl/simpleascoding/tutoringplatform/domain/user/User.java, src/main/java/pl/simpleascoding/tutoringplatform/dto/AdvertisementDTO.java, src/main/java/pl/simpleascoding/tutoringplatform/dto/CreateAdvertisementDTO.java, src/main/java/pl/simpleascoding/tutoringplatform/exception/UserIsNotATeacherException.java, src/main/java/pl/simpleascoding/tutoringplatform/repository/AdvertisementRepository.java, src/main/java/pl/simpleascoding/tutoringplatform/service/advertisement/AdvertisementModelMapper.java, src/main/java/pl/simpleascoding/tutoringplatform/service/advertisement/AdvertisementService.java, src/main/java/pl/simpleascoding/tutoringplatform/service/advertisement/AdvertisementServiceImpl.java
- created `advertisement` package in domain
- created `advertisement` package in domain
- created `Advertisement` class in `advertisement` package
- created `AdvertisementCategory` enum in `advertisement` package
- added list of advertisements to `User` class
- created `AdvertisementRepository` interface
- created `advertisement` package in `service` package
- created `AdvertisementModelMapper` interface, which is not actually used, because modelmapper probably cant map username from user by default
- created `AdvertisementService` and it's implementation with necessary methods like: `createAdvertisement`
=> feature_adding_advertisement
